"use client";

import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { getMessageText } from "../components/message-content";
import { supabase } from "../../lib/supabase";

const examples = ["Rynek AI w Polsce — trendy, firmy, prognozy na 2026", "Porównanie platform e-commerce: Shopify vs WooCommerce vs PrestaShop", "Wpływ pracy zdalnej na produktywność — badania i statystyki", "Rynek nieruchomości w Krakowie — ceny, trendy, prognozy"];
type SavedReport = { id: string; topic: string; content: string; created_at: string };

function inline(text: string) {
  return text.split(/(\*\*[^*]+\*\*|\[[^\]]+\]\([^\)]+\))/g).filter(Boolean).map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>;
    const link = part.match(/^\[([^\]]+)\]\(([^\)]+)\)$/);
    return link ? <a href={link[2]} key={index} rel="noreferrer" target="_blank">{link[1]}</a> : <span key={index}>{part}</span>;
  });
}

function ReportMarkdown({ text }: { text: string }) {
  const lines = text.replace(/\r/g, "").split("\n"); const blocks: React.ReactNode[] = []; let index = 0;
  while (index < lines.length) {
    const line = lines[index].trim(); if (!line) { index++; continue; }
    if (line.startsWith("#")) { const level = Math.min(line.match(/^#+/)?.[0].length ?? 2, 3); const Heading = `h${level}` as "h1" | "h2" | "h3"; blocks.push(<Heading key={index}>{inline(line.replace(/^#+\s*/, ""))}</Heading>); index++; continue; }
    if (line.startsWith("|") && index + 1 < lines.length && /^\|?\s*:?-{3,}/.test(lines[index + 1])) { const rows: string[][] = []; while (index < lines.length && lines[index].trim().startsWith("|")) { rows.push(lines[index].split("|").slice(1, -1).map((cell) => cell.trim())); index++; } const header = rows.shift() ?? []; blocks.push(<div className="report-table-wrap" key={index}><table><thead><tr>{header.map((cell, cellIndex) => <th key={cellIndex}>{inline(cell)}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex}>{inline(cell)}</td>)}</tr>)}</tbody></table></div>); continue; }
    if (/^[-*]\s+/.test(line) || /^\d+\.\s+/.test(line)) { const ordered = /^\d+\./.test(line); const items: string[] = []; while (index < lines.length && (ordered ? /^\d+\.\s+/.test(lines[index].trim()) : /^[-*]\s+/.test(lines[index].trim()))) { items.push(lines[index].trim().replace(ordered ? /^\d+\.\s+/ : /^[-*]\s+/, "")); index++; } const List = ordered ? "ol" : "ul"; blocks.push(<List key={index}>{items.map((item, itemIndex) => <li key={itemIndex}>{inline(item)}</li>)}</List>); continue; }
    if (line.startsWith(">")) { blocks.push(<blockquote key={index}>{inline(line.replace(/^>\s?/, ""))}</blockquote>); index++; continue; }
    const paragraph = [line]; index++; while (index < lines.length && lines[index].trim() && !lines[index].trim().startsWith("#") && !lines[index].trim().startsWith("|") && !/^[-*]\s+/.test(lines[index].trim())) { paragraph.push(lines[index].trim()); index++; } blocks.push(<p key={index}>{inline(paragraph.join(" "))}</p>);
  }
  return <>{blocks}</>;
}

export default function ReportPage() {
  const [input, setInput] = useState(""); const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [saveError, setSaveError] = useState(""); const [savedReports, setSavedReports] = useState<SavedReport[]>([]); const [selectedReport, setSelectedReport] = useState<SavedReport | null>(null); const [historyState, setHistoryState] = useState<"loading" | "ready" | "error">("loading"); const [deletingId, setDeletingId] = useState<string | null>(null); const transport = useMemo(() => new DefaultChatTransport({ api: "/api/report" }), []); const { messages, sendMessage, status, error, setMessages } = useChat({ transport }); const loading = status === "submitted" || status === "streaming"; const report = [...messages].reverse().find((message) => message.role === "assistant");
  async function authHeaders() { const { data: { session } } = await supabase.auth.getSession(); if (!session?.access_token) throw new Error("Zaloguj się, aby korzystać z historii raportów."); return { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }; }
  async function loadHistory() { setHistoryState("loading"); try { const response = await fetch("/api/reports", { headers: await authHeaders() }); const payload = await response.json() as { reports?: SavedReport[]; error?: string }; if (!response.ok) throw new Error(payload.error ?? "Nie udało się pobrać historii."); setSavedReports(payload.reports ?? []); setHistoryState("ready"); } catch { setHistoryState("error"); } }
  useEffect(() => { void loadHistory(); }, []);
  async function generate(topic: string) { if (!topic.trim() || loading) return; setInput(""); setSelectedReport(null); setSaveState("idle"); setSaveError(""); await sendMessage({ text: `Przygotuj profesjonalny raport biznesowy na temat: ${topic.trim()}` }); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void generate(input); }
  const activeText = selectedReport?.content ?? (report ? getMessageText(report) : ""); const activeTitle = selectedReport?.topic ?? "Gotowy raport";
  async function copyReport() { if (activeText) await navigator.clipboard.writeText(activeText); }
  async function saveReport() { if (!report || saveState === "saving") return; setSaveState("saving"); setSaveError(""); try { const response = await fetch("/api/reports", { method: "POST", headers: await authHeaders(), body: JSON.stringify({ topic: getMessageText(report).match(/^#\s*📊?\s*Raport:\s*(.*)$/m)?.[1] ?? "Raport AI", content: getMessageText(report) }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Nie udało się zapisać raportu."); setSaveState("saved"); await loadHistory(); } catch (saveError) { setSaveState("error"); setSaveError(saveError instanceof Error ? saveError.message : "Nie udało się zapisać raportu."); } }
  async function deleteReport(id: string) { if (!window.confirm("Usunąć zapisany raport?")) return; setDeletingId(id); try { const response = await fetch("/api/reports", { method: "DELETE", headers: await authHeaders(), body: JSON.stringify({ id }) }); if (!response.ok) throw new Error(); if (selectedReport?.id === id) setSelectedReport(null); await loadHistory(); } finally { setDeletingId(null); } }
  return <main className="report-shell"><section className="report-panel"><header className="report-header"><h1>📊 Generator raportów</h1><p>Opisz temat — agent napisze raport biznesowy oparty na źródłach</p></header><form className="report-form" onSubmit={submit}><label htmlFor="report-topic">O czym ma być raport?</label><input id="report-topic" onChange={(event) => setInput(event.target.value)} placeholder="Np. Rynek AI w Polsce w 2026 roku..." value={input} /><button className="report-primary" disabled={loading || !input.trim()} type="submit">📊 {loading ? "Generuję raport..." : "Generuj raport"}</button><div className="report-examples">{examples.map((example) => <button disabled={loading} key={example} onClick={() => void generate(example)} type="button">{example}</button>)}</div></form><section className="report-history"><div className="report-history-heading"><h2>Historia zapisanych raportów</h2><button disabled={historyState === "loading"} onClick={() => void loadHistory()} type="button">Odśwież</button></div>{historyState === "loading" && <p>Wczytywanie historii...</p>}{historyState === "error" && <p className="report-save-error">Nie udało się pobrać historii. Zaloguj się i upewnij się, że migracja SQL została uruchomiona.</p>}{historyState === "ready" && (savedReports.length ? <div className="report-history-list">{savedReports.map((item) => <article className="report-history-item" key={item.id}><button className="report-history-open" onClick={() => setSelectedReport(item)} type="button"><strong>{item.topic}</strong><time>{new Intl.DateTimeFormat("pl-PL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.created_at))}</time></button><button className="report-history-delete" disabled={deletingId === item.id} onClick={() => void deleteReport(item.id)} type="button">{deletingId === item.id ? "Usuwanie..." : "Usuń"}</button></article>)}</div> : <p>Nie masz jeszcze zapisanych raportów.</p>)}</section>{error && <p className="report-error">Nie udało się wygenerować raportu. Spróbuj ponownie.</p>}{activeText && <div className="report-result"><div className="report-result-actions"><strong>{activeTitle}</strong><div><button onClick={() => void copyReport()} type="button">📋 Kopiuj do schowka</button>{!selectedReport && <button disabled={saveState === "saving" || saveState === "saved"} onClick={() => void saveReport()} type="button">{saveState === "saved" ? "✓ Zapisano" : saveState === "saving" ? "Zapisywanie..." : "💾 Zapisz w bazie"}</button>}</div></div>{saveError && <p className="report-save-error">{saveError}</p>}<div className="report-markdown"><ReportMarkdown text={activeText} /></div></div>}{loading && <p className="report-loading">Agent zbiera dane i analizuje źródła...</p>}{messages.length > 0 && !loading && <button className="report-clear" onClick={() => { setMessages([]); setSelectedReport(null); }} type="button">Wyczyść i przygotuj nowy raport</button>}</section></main>;
}
