"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import { AdminNavigation } from "../../components/admin-navigation";

type Data = { generatedAt: string; stats: { users: number; conversations: number; tokensToday: number; costTodayUsd: number }; tokenDays: { day: string; tokens: number }[]; conversationDays: { day: string; conversations: number }[]; endpointTokens: { endpoint: string; tokens: number }[]; recentConversations: { id: string; email: string; title: string; createdAt: string; messageCount: number }[]; };
const number = new Intl.NumberFormat("pl-PL");
function Chart({ rows, field, title }: { rows: Array<{ day: string; tokens?: number; conversations?: number }>; field: "tokens" | "conversations"; title: string }) { const value = (row: { tokens?: number; conversations?: number }) => row[field] ?? 0; const max = Math.max(...rows.map(value), 1); return <article className="usage-chart"><h2>{title}</h2><div className="usage-bars">{rows.map((row) => <div key={row.day}><span>{number.format(value(row))}</span><i style={{ height: `${Math.max(4, value(row) / max * 100)}%` }} /><small>{row.day.slice(5).replace("-", ".")}</small></div>)}</div></article>; }
export default function AdminDashboardPage() { const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); useEffect(() => { void (async () => { try { const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error("Sesja wygasła."); const response = await fetch("/api/admin/dashboard", { headers: { Authorization: `Bearer ${session.access_token}` } }); const payload = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(payload.error); setData(payload); } catch (caught) { setError(caught instanceof Error ? caught.message : "Błąd pobierania danych."); } })(); }, []); if (error) return <main className="usage-dashboard"><p>{error}</p></main>; if (!data) return <main className="usage-dashboard"><p>Wczytywanie danych…</p></main>; return <main className="usage-dashboard"><header><div className="admin-header-topline"><p>ADMINISTRACJA</p><AdminNavigation /></div><h1>Dashboard użycia</h1><span>Stan na {new Date(data.generatedAt).toLocaleString("pl-PL")}</span></header><section className="usage-kpis"><article><span>Użytkownicy</span><b>{number.format(data.stats.users)}</b><small>z rozmową</small></article><article><span>Rozmowy</span><b>{number.format(data.stats.conversations)}</b><small>łącznie</small></article><article><span>Tokeny dziś</span><b>{number.format(data.stats.tokensToday)}</b><small>wejściowe i wyjściowe</small></article><article><span>Koszt dziś</span><b>${data.stats.costTodayUsd.toFixed(4)}</b><small>$0,15 / 1 mln tokenów</small></article></section><section className="usage-charts"><Chart rows={data.tokenDays} field="tokens" title="Tokeny dziennie" /><Chart rows={data.conversationDays} field="conversations" title="Rozmowy dziennie" /><article className="usage-endpoints"><h2>Tokeny per endpoint</h2>{data.endpointTokens.length ? <ul>{data.endpointTokens.map((item) => <li key={item.endpoint}><span>{item.endpoint}</span><b>{number.format(item.tokens)}</b></li>)}</ul> : <p>Brak danych użycia.</p>}</article></section><section className="usage-recent"><h2>Ostatnie rozmowy</h2>{data.recentConversations.length ? <table><thead><tr><th>Użytkownik</th><th>Tytuł</th><th>Data</th><th>Wiadomości</th></tr></thead><tbody>{data.recentConversations.map((row) => <tr key={row.id}><td>{row.email}</td><td>{row.title}</td><td>{new Date(row.createdAt).toLocaleString("pl-PL")}</td><td>{row.messageCount}</td></tr>)}</tbody></table> : <p>Brak zapisanych rozmów.</p>}</section></main>; }
